### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by davegson**

### CODE REVIEW

**Comment by davegson** [comment]
I pushed the fix for the most urgent bug - logo distortion fix - directly onto master.

Both the **new/overview** and the **new/about-short** section are broken on a tablet - so I won't be merging this as of now. 

Screen Shot 2019-11-14 at 7 51 08 PM

I'll merge this as soon as the tablet issues are fixed

**Comment by davegson** [comment]
Screenshot_2019-11-25 Safing

Nope - responsiveness is still broken

**Comment by LukeSeers** [comment]
I've tested it on browser stack and it seems to be fine,

**Comment by davegson** [comment]
@LukeSeers the screenshot is from a downsized Firefox. It's not fine in my book - especially the top section looks underwhelming and needs fixing

**Comment by LukeSeers** [comment]
hopefully that will fix the issues :/

**Comment by davegson** [comment]
finally got back to this, sorry, still is broken :/

Screen Shot 2020-01-09 at 12 53 44 PM

**Comment by davegson** [comment]
closing due to age, also, the new design is on its way ;)

**Pull request closed without merging**
