### PR TITLE
Feature/readme change detection

### PR DESCRIPTION
**Pull request by philippklemmer**
Added instruction so people who work on this project, immediately can have template change detection available instead of restarting the docker process if something changed.

### CODE REVIEW

**Comment by davegson** [comment]
Hi @philippklemmer - thank you for your contributions! Regarding this PR, would you mind explaining a bit more what it does? I [checked the docs](https://jekyllrb.com/docs/configuration/options/) and it just generically explains to: force polling. Is the idea to auto-update the page in the browser after you save a file?

Could you maybe lead me in the right direction?

**Comment by davegson** [comment]
also, this branch is based off another PR - so it includes the uppercase commit as well ;) No big issue - since I want to accept it anyway, but just so you know.

**Comment by philippklemmer** [comment]
> also, this branch is based off another PR - so it includes the uppercase commit as well ;) No big issue - since I want to accept it anyway, but just so you know.

**Comment by philippklemmer** [comment]
Sorry for the late reply. I'm sorry, that it's based of another branch. I will change that right now. 

Current work flow is: 

Make changes in Scss files - instant update in your working environment
Make changes to template files - nothing has changed, because the server needs a restart
 
If you add the argument to the starting command it will also restart the server, whenever something changed in the templates. It's much more pleasant to work with it.

**Comment by philippklemmer** [comment]
Here is the link to the new one:

https://github.com/safing/web/pull/20

**Comment by davegson** [comment]
I wrote a reply on #20, and do not worry about speed - this stuff is meant to work asynchronously, whenever you have time ;)

**Pull request closed without merging**
